-- Add recurrence and scheduling columns to company_event.
-- recurrence_group_id links events generated by a recurrence pattern.
-- component_id ties the event to a specific curriculum component.
-- allow_on_holiday marks events that should not be cancelled on holidays.

ALTER TABLE company_event
  ADD COLUMN IF NOT EXISTS recurrence_group_id UUID REFERENCES recurrence_group(id),
  ADD COLUMN IF NOT EXISTS component_id UUID,
  ADD COLUMN IF NOT EXISTS allow_on_holiday BOOLEAN DEFAULT FALSE;

CREATE INDEX idx_company_event_recurrence_group ON company_event(recurrence_group_id) WHERE recurrence_group_id IS NOT NULL;
CREATE INDEX idx_company_event_component ON company_event(component_id) WHERE component_id IS NOT NULL;
